// Generated by CoffeeScript 1.7.1
var FS, grunt, _;

grunt = require('grunt');

_ = require('underscore');

FS = require('fs');

module.exports = function(srcPath, destPath, copyOptions) {
  var copyCount, excludePatterns, filePatterns, filesMap;
  copyCount = 0;
  copyOptions = _.extend({
    encoding: grunt.file.defaultEncoding,
    process: false,
    noProcess: [],
    copyExcludes: [],
    mode: false,
    keepDest: true
  }, copyOptions);
  if (copyOptions.keepDest === false) {
    grunt.verbose.writeln("Deleting " + destPath.yellow + " ...");
    grunt.file["delete"](destPath, {
      force: true
    });
  }
  excludePatterns = copyOptions.copyExcludes.map(function(pattern) {
    return '!' + pattern;
  });
  filePatterns = ['**/*.*'].concat(excludePatterns);
  filesMap = grunt.file.expandMapping(filePatterns, destPath, {
    expand: true,
    filter: 'isFile',
    cwd: srcPath
  });
  filesMap.forEach(function(filePair) {
    var dest, src;
    src = filePair.src;
    dest = filePair.dest;
    grunt.verbose.writeln("Copying " + src.cyan + " -> " + dest.cyan);
    grunt.file.copy(src, dest, copyOptions);
    if (copyOptions.mode !== false) {
      fs.chmodSync(dest, copyOptions.mode === true ? fs.lstatSync(src).mode : copyOptions.mode);
    }
    return copyCount++;
  });
  if (copyCount) {
    grunt.log.write("Copied " + (copyCount.toString().cyan) + " files");
  }
  return grunt.log.writeln();
};
